osuAkatsuki/bancho.py

- constants/commands.py
makes code structure easier to follow, and makes it easier to add more commands in future too. :)
> use a decorator to register command information

- README.md
- config.sample.py
- console.py
- constants/commands.py
- constants/gamemodes.py
- db.sql
- events/bancho.py
- events/web.py
- handlers.py
- main.py
- objects/beatmap.py
- objects/collections.py
- objects/player.py
- objects/score.py
- packets.py
Preparing for production - autopilot added along with pp changes to match, added the ability to deprecate both /web handlers and bancho packets, heavily refactored gamemodes and cleaned up a lot.
The server is probably 90% complete, now.. not including frontend of course :)
> v2.7.0 - Autopilot, handler deprecation, refactoring & general improvements/optimizations.

- config.sample.py
- console.py
- constants/clientflags.py
- constants/commands.py
- constants/countries.py
- constants/privileges.py
- constants/regexes.py
- db.sql
- events/api.py
- events/bancho.py
- events/web.py
- handlers.py
- main.py
- nginx.conf
- objects/beatmap.py
- objects/channel.py
- objects/collections.py
- objects/match.py
- objects/player.py
- objects/score.py
- packets.py
Got quite a bit done in this update, I've been working pretty well this week.
A few notable things from the updates:
- In-game registration
- Simple mail system (sending dms ingame will enqueue it for when a player next logs in)
- Using __doc__ for command docstrings - basically this was done in a much less clean fashion before
- API cleanup - added a basic event logging table to sql called `logs`, and started using it in places like Player.ban().
And more general overall code maintenance and improvements.
Cheers!
> v2.7.5 - Significant work all around

- README.md
+ Add Python3.9 install instructions.
* Clarify instructions further.
> Add Python 3.9 install instructions

- CONTRIBUTING.md
Addition to #36.
- Remove pointless sentence on #L33.
* Fix invalid link on #L128.
> 📝 Fix grammar and broken link in CONTRIBUTING.md

- main.py
> Fixed config socket being ignored

- objects/beatmap.py
> Fix: properly beatmap url for embeds

- constants/regexes.py
A very small problem,
after resolving this, grouping matching will work correctly.
[https://regexr.com/5pitg](https://regexr.com/5pitg)
> fix: regexes.mapfile

- constants/commands.py
- domains/cho.py
- objects/player.py
This behavior replicates Bancho, as seen in this video.
https://streamable.com/vth5kv
Given how explicitly self-friending is mentioned in code, I believe @cmyui intentionally created this functionality. If so, I propose a follow up commit which allows toggling self-friending in config. In my own experience I find self-friending jarring, but others may have differing opinions.
> No longer friends with yourself.

- domains/osu.py
Added last seen timestamp when user is offline to get_player_status request.
> Updated get_player_status api request

- domains/osu.py
> fix stats updating to wrong mode

- main.py
nginx is NOT a dependency.
Docker users have to hack around it
https://github.com/ledlamp/gulag-dockerized/blob/1eb4531d66afb0d153f3d7482830d0e395ae18cb/source/gulag.Dockerfile#L6
https://github.com/catgirlmoe/gulag/blob/0c3defbc98d8bb2f7050ade3a6507bc6d4c96145/Dockerfile#L22-L23
y dont these embed >:(
> Delete nginx check

- constants/commands.py
- domains/cho.py
- objects/score.py
Full implementation of peace-performance for taiko, catch and mania. Also updated /np and !with command to use peace-performance.
> Implemented peace-performance for non std modes.

- app/api/osu.py
> :trollface: 😳 

- app/api/domains/api.py
> actually get scores even if user isn't logged in

- app/constants/commands.py
Now it works, chache goes vroooom.
> Add !clan leave command

- app/constants/commands.py
- app/objects/player.py
- migrations/base.sql
- tools/migrate_logs.py
What changes:
- Logging format (now split between action and (optional) reason)
- Allows people to get the context & reason for a log without using regex
Includes a migration script to fix old logs. Looking at a merge once other branches are merged first, to avoid conflicts.
> Improve gulag logging

- app/commands.py
This got changed in 4.0 if I remember correctly.
> Change dangerous to developer

- app/objects/player.py
> Update (redis) leaderboard cache when modifying restriction status of a player

- app/api/domains/api.py
> display clan id in api request

- app/api/domains/osu.py
> fix overall ranking stats

- app/api/domains/osu.py
> fix peppy breaking lbs

- app/objects/beatmap.py
Maybe I'm bad at english and if I'm wrong it's quite funny issue, but shouldn't this be "We keep"
> Typo in beatmap.py

- app/commands.py
- requirements.txt
Examples:
!givedonator minisbett 5m
!givedonator minisebtt 5minutes
!givedonator minisbett 3h17m2s
!givedoantor minisbett 10weeks
!givedonator minisbett 3.5d
> Add givedonator command using pytimeparse's timespan parsing

- app/api/domains/api.py
- app/commands.py
- app/constants/regexes.py
- app/objects/collections.py
- app/objects/player.py
In the current state, the command won't run as there is no `donor_end` in the Player object.
> Add donor_end to player object, use pytimeparse consistently

- README_CN.md
I tried to translate the README file to Chinese, and added some tips according to my own experience
(If there are some errors, welcome to tell me about them, thanks~)
> Add the Chinese translation of README file

- README_CN.md
Fix console image in Chinese translation
> Fix console image in Chinese translation

- app/api/domains/cho.py
sorry, I forgot to test it on other builds LOL
> Actually fix release stream bug

- .env.example
- app/settings.py
- app/utils.py
- main.py
coding this from 33,000 feet in the sky after a glass of wine btw
> v4.6.0 - refactor connected service checks & configuration

- app/api/domains/api.py
What I did:
1. Add plays and playtime sorts on leaderboard when api request
> More sorts on leaderboard

- README_CN.md
removed ava.py (followed the English version)
> removed ava.py

- app/objects/score.py
It should be "its" (possessive pronoun) instead of "it's" because it refers to the score object.
> Spelling mistake

- README.md
- README_DE.MD
- app/api/domains/api.py
- app/api/domains/osu.py
- app/api/init_api.py
- app/bg_loops.py
- app/commands.py
- app/constants/mods.py
- app/discord.py
- app/objects/beatmap.py
- app/objects/player.py
- app/packets.py
- app/state/sessions.py
- app/utils.py
> Helping out with grammar/spelling/... + README translation to german

- app/api/domains/api.py
[works well on my server](https://api.halcyon.moe/search?src=j), thought it would be beneficial enough to bring to base bpy
written together with [syswhite](https://github.com/SysWhiteDev)
> add /search_players api route

- app/api/domains/api.py
- app/api/domains/osu.py
- app/state/services.py
some preliminary stuff for refactoring to come
> refactor: delete manual acquiring of db conns

- app/api/domains/osu.py
- app/objects/beatmap.py
kudos to @JKBGL for the bug reports
> fix: various beatmap bugs

- README_CN.md
Follows the #332
Updated some unclear translation
> Update the Chinese translation

- Makefile
> [scripts] Add `Makefile`

- app/api/domains/cho.py
- app/commands.py
- app/packets.py
> fix: outdated variable names

- app/api/domains/api.py
- app/api/domains/cho.py
- app/api/domains/osu.py
- app/commands.py
- app/discord.py
- app/objects/beatmap.py
- app/objects/collections.py
- app/objects/match.py
- app/objects/player.py
- app/settings.py
- app/state/services.py
- app/state/sessions.py
- main.py
- tools/proxy.py
- tools/recalc.py
> chore: remove all walrus operator usage

- app/commands.py
- app/objects/player.py
One of the things I added on cs0su for convenience, would also make it consistent as there are also reasons for unrestrictions
> Add reason to unsilence command

- .github/pull_request_template.md
- Makefile
addresses concerns raised on [discord](https://discord.com/channels/748687781605408908/748688897168375819/1063601775304769697)
Added `make lint` command, auto-enabled pre-commit on dev installs
> tools: enable pre-commit for dev install; add lint

- .github/SECURITY.md
> docs: add `SECURITY.md`

- README.md
Update the readme directory structure to separate v1 and v2 and add the resources to v2.
> docs: Update readme for API v2

- README_CN.md
Updated directory structure and translations
> fix: updated directory structure in chinese readme

- README.md
> docs: update migrations path

- Pipfile
- Pipfile.lock
- README.md
- README_CN.md
- README_DE.MD
- requirements-dev.txt
- requirements.txt
> chore: add akatsuki-pp-py from pypi

- app/objects/beatmap.py
since Kitsu got rebranded to osu.direct, the url changed
> change kitsu to osu.direct

- app/api/domains/cho.py
display more information in the "bancho" page, key to judge if it's safe to restart server without login using osu client.
> interactive ui for online players & matches on GET /c.ppy.sh page

- app/api/domains/cho.py
i've also removed the unnecessary GameMode() conversions as mode on match is typehinted as int anyway
> fix: osu erroring on map change when mode is >= 4

- app/api/v1/api.py
- app/usecases/performance.py
TypedDicts were not kept up to date with code in:
- #348
> fix typing errors in performance calc from #348

- .github/pull_request_template.md
> add manual testing to pr checklist

- README.md
> Update akatsuki.pw domain to akatsuki.gg

- README.md
- tools/generate_cf_dns_records.sh
removed endpoints which are not needed
> docs: remove unused endpoints from cloudflare tutorial

- app/api/v1/api.py
fixes https://github.com/osuAkatsuki/bancho.py/issues/452
https://github.com/osuAkatsuki/bancho.py/issues/452
> fix: remove as_vanilla call from get_match api endpoint

- app/api/domains/osu.py
there was no success message initially, leading to the client to return "Internal Server Error" instead of any success message -- this fixes that
> fix: add return value for `/web/osu-addfavourite.php`

- README.md
- README_CN.md
- README_DE.MD
hello, updated readme files since i've faced some issues doing manual installation
> Fix nginx config file name in readme files

- app/usecases/performance.py
Fixes this: https://discord.com/channels/748687781605408908/790425632017219605/1138050631064637440
> Fix rosupp DTNC pp calculation meme

- app/objects/beatmap.py
Hotfix for my incompetency
Fixes broken code I added in #493
> fix: incorrect handling of BeatmapApiResponse response

- app/_typing.py
- app/objects/collections.py
- app/repositories/achievements.py
- app/repositories/channels.py
- app/repositories/clans.py
- app/repositories/maps.py
- app/repositories/players.py
- app/repositories/scores.py
- app/repositories/stats.py
> impl: implement unset pattern

- Makefile
> fix: re-enable running unit tests post-update

- docker/banchopy/Dockerfile
Type fix PR purged `make run-prod` in favour of `make run` being the only run command, which wasn't reflected in the Dockerfile, so currently it just crashes.
> fix: dockerfile

- Pipfile
- Pipfile.lock
- app/api/init_api.py
- app/commands.py
- app/utils.py
- mypy.ini
Removes any code that was written specifically for Linux in mind in preparation for Windows support.
Note that uvloop still needs to be replaced with winloop before Windows will properly work.
Resolves #502
> fix: remove any linux specific implementations

- app/objects/beatmap.py
> Set an absolute limit of 1 day on beatmaps cache; generalize some code

- app/utils.py
> Remove achievement images mirror

- .github/docs/wiki/Breaking-changes.md
- .github/docs/wiki/locale/de-DE/Breaking-changes-de-DE.md
- .github/docs/wiki/locale/zh-CN/Breaking-changes-zh-CN.md
> docs: update breaking changes

- app/api/domains/osu.py
- app/objects/collections.py
- app/repositories/achievements.py
- app/state/sessions.py
- app/usecases/achievements.py
Removes achievement state aswell as the object in favour of usecases
> refactor: remove Achievement object & achievements state

- app/api/domains/cho.py
- app/api/domains/osu.py
- app/objects/collections.py
- app/objects/player.py
- app/repositories/achievements.py
- app/repositories/user_achievements.py
- app/state/sessions.py
- app/usecases/achievements.py
- app/usecases/user_achievements.py
Part of a large plan to refactor the codebase into more digestable pieces, in preparation for stateless architecture
> refactor: replace Player.achievements with usecases

- mypy.ini
> Add mypy pydantic plugin

- .github/workflows/docker-build.yaml
silently failed because it does not pass the argument on false
as per: https://docs.docker.com/build/ci/github-actions/test-before-push/
> fix: `outputs` and `push` cannot be used together

- .github/workflows/docker-build.yaml
> fix: improper syntax for .env

- .github/workflows/docker-build.yaml
Hopefully the last one in this saga
- Moved login step to be next to push step
- Changed build step tags to prevent overriding images locally
- Added commit sha tags alongside latest tag
Dry run output: [act.log](https://github.com/osuAkatsuki/bancho.py/files/12725344/act.log)
Tested locally and it caches steps correctly.
> feat: improve build workflow

- .github/pull_request_template.md
pre-commit-ci already gives us this info
> Reduce number of required checkboxes for prs

- Pipfile.lock
- app/commands.py
- app/objects/player.py
- app/repositories/logs.py
> refactor: logs repository

- app/api/domains/cho.py
- app/api/domains/osu.py
- app/api/middlewares.py
- app/api/v1/api.py
- app/api/v2/common/responses.py
- app/commands.py
- app/constants/mods.py
- app/logging.py
- app/objects/beatmap.py
- app/objects/match.py
- app/packets.py
- app/utils.py
- main.py
> Do or remove TODOs throughout the code

- app/api/domains/cho.py
- app/objects/player.py
- app/packets.py
- tests/unit/test_packets.py
> osu! client login refactoring, fixes, cleanup

- Pipfile
- Pipfile.lock
- requirements-dev.txt
- requirements.txt
Came across this issue while trying to set up my local dev environment only to find out that somehow pydantic was not a dep???
> chore: knock some sense into dependencies

- app/api/domains/osu.py
> Remove /web/osu-error.php handler

- Pipfile.lock
- app/api/domains/cho.py
- app/commands.py
- app/objects/collections.py
- app/objects/player.py
> rename some vars across the codebase (mainly for clarity)

- app/commands.py
- app/repositories/map_requests.py
> refactor: map_requests repository

- tools/recalc.py
> fix: cherrypick argument fixes for recalc script

- .github/workflows/test.yaml
> fix: run application test on prs

- .github/workflows/test.yaml
> fix: only run tests if relevant files change

- .github/workflows/test.yaml
- Dockerfile
- Makefile
- app/api/init_api.py
- app/utils.py
- docker-compose.test.yml
- docker-compose.yml
- main.py
- scripts/run-tests.sh
- tests/conftest.py
> Isolated global state for each run of a test suite

- app/api/domains/cho.py
- app/repositories/client_hashes.py
> refactor: client_hashes repository

- tests/conftest.py
> Mock achievement downloads in tests (2x speedup to suite)

- tests/conftest.py
> Prefer less permissive mock url pattern

- app/api/domains/cho.py
- app/objects/collections.py
- app/objects/player.py
The complexity in some of the objects (especially things such as constructors) has been a problem on my mind for a while. Starting with the `Player` class here, and I'll move onto others shortly. Ideally this refactoring effort should make these APIs more understandable, reusable and testable.
> Simplify the `Player` object/class

- .github/workflows/test.yaml
- .gitignore
- poetry.lock
- pyproject.toml
- scripts/run-tests.sh
This PR adds test coverage to our test suite. Coverage allows us to see what code flows we are testing, and helps identify untested code.
> Setup test coverage (text & html reports available in CI)

- app/api/domains/cho.py
- app/objects/match.py
> Handle private match history case in match creation

- app/objects/match.py
> Scrim fixes and cleanup

- app/state/services.py
> Fix migrations not running if never run before

- migrations/base.sql
- migrations/migrations.sql
- pyproject.toml
This PR is a first-sweep at improving some database performance of bancho.py.
This PR adds 27 new basic indices -- nothing fancy, e.g. no composite indices yet -- just a first sweep.
> Basic indices for SQL

- app/api/domains/cho.py
- app/api/init_api.py
- app/commands.py
- app/objects/beatmap.py
- app/objects/collections.py
- app/objects/player.py
- app/state/services.py
> Remove use of passed-around/reused db conns

- app/api/v1/api.py
> Ensure `/get_mappool` doesn't crash if pool creator is not in a clan

- app/adapters/database.py
- app/timer.py
> Instrument & log all database calls

- app/repositories/users.py
> Fix query selecting users count from DB

- app/api/v1/api.py
- adds `player_country` to /v1/get_map_scores
> add missing country field to get_map_scores

- app/api/v1/api.py
Grthusdd pt qwas masdwe switth deededt
> misc: remove useless note

- app/api/domains/osu.py
Added beatmap search by checksum in case if user trying to load replay with beatmap that doesn't imported in their client.
> feat(direct): added checksum beatmap search

- .github/workflows/test.yaml
> fix: wait for containers to be healthy before attempting to run tests

- .github/workflows/test.yaml
> fix: remove deprecated docker-compose command

- app/api/domains/osu.py
fix: stats updating to wrong mode due to unbelievable gm_stats in score submission
Issue: #678
> fix: stats updating to wrong mode due to unbelievable gm_stats in score submission

- docker-compose.test.yml
- docker-compose.yml
> fix typo in docker-compose

- app/commands.py
> fix: clean up !givedonator command type error

- app/api/domains/cho.py
- app/api/domains/osu.py
- app/api/init_api.py
- app/api/v1/api.py
- app/commands.py
- app/objects/channel.py
- app/objects/collections.py
- app/objects/match.py
- app/objects/player.py
- app/packets.py
- app/state/services.py
- pyproject.toml
- tools/recalc.py
> More strict mypy config

- alembic/versions/158030827560_base_schema.py
- app/repositories/comments.py
- app/repositories/ingame_logins.py
- app/repositories/logs.py
- app/repositories/maps.py
- app/repositories/performance_reports.py
- app/repositories/startups.py
- app/repositories/tourney_pool_maps.py
- app/repositories/tourney_pools.py
- app/repositories/users.py
- docker-compose.test.yml
- docker-compose.yml
> chore: fix alembic migrations

- Dockerfile
removes version pin from the Dockerfile which causes build to fail
https://discord.com/channels/748687781605408908/748687781605408911/1411416892576501862
&
> Update Dockerfile to remove specific version of build-essential
