- Pipfile
- README.md
- requirements.txt
This makes it a lot easier to manage dependencies. You will still need to generate a lockfile (just run `pipenv lock`).
> Add Pipenv (docker prerequisite)

- README.md
@Faithy3 asked me to make a PR for this, as he said it's required to build oppai
> Add build-essential to instructions

- packets.py
When trying to write non-English characters to the packets, it will get an incorrect length.
Incorrect length will cause the osu! client to not display some packets normally (such as notifications)
len("h") -> 1 √
len("嗨") -> 1 ×
len("嗨".encode()) -> 3 √
> Tiny fix: correct byte length

- domains/osu.py
Bancho's implementation of the password length check had a minimum of 8 characters. This means that a password can be equal to or greater than 8. Currently, this is not the case. 
(very important pull request lol)
> made < into <=

- main.py
Use env in shebang, as on some systems python might not be where you expect it to be
Source: https://stackoverflow.com/questions/6908143/should-i-put-shebang-in-python-scripts-and-what-form-should-it-take
> Fix main.py shebang

- ext/nginx.conf
this worked on ubuntu 20.04
closes #107 
todo maybe update the readme for 20.04 as well, cuz now u can just `apt install python3.9 python3-pip`. also python3.9-dev and python3.9-distutils don't seem to be needed
o btw instead of `git submodule init && git submodule update` just git clone `--recursive`.
o and gulag builds oppai for u so that part can be omitted too
> ubuntu 20.04 support

- README.md
- domains/osu.py
- ext/requirements.txt
- main.py
- misc/context.py
- misc/utils.py
- objects/glob.py
- objects/player.py
Uses an aioredis implementation to manage global and country ranks, allowing for more accurate ranking systems and for ranks to be grabbed outside of gulag's memory (example: API). Also allows https://github.com/cmyui/gulag/issues/87 to be closed.
> Implement proper ranking of users (redis)

- objects/score.py
In commit https://github.com/cmyui/gulag/commit/b1694fc08a235ffd423b850987514b632cabb423, some cleanups in score submission caused the indexes of score data to be inaccurate.
> Fix score submission

- ext/nginx.conf
This can lead to misunderstanding. Devserver is in stable since like 8 months.
> Devserver is supported

- .gitmodules
- README.md
- app/api/domains/cho.py
- app/commands.py
- app/objects/score.py
- app/utils.py
- settings.py
Currently, we are using a ctypes wrapper around oppai-ng for speed, which is great, however prone to bugs (see https://github.com/cmyui/gulag/issues/138).
I made a new wrapper for oppai based on cmyui’s fork made with pybind11 to directly compile a python binding eliminating any possible bugs, and (partly) supporting Windows on the way.
I created this pull request instead of merging as I need some testers to confirm this branch is stable, so please reach out in the gulag Discord! Note when testing that oppai is only used for osu!standard in gulag.
closes #138
> Use pybind11 for oppai-ng bindings

- app/api/domains/cho.py
- app/api/domains/osu.py
- app/commands.py
- app/constants/regexes.py
- app/objects/match.py
- app/objects/player.py
- app/objects/score.py
- app/utils.py
- add score submission 'anticheat' (server-side validation of score checksum, unique ids, client hashes, osu version)
- stored client details (client hashes, adapters, ip, osu version) in Player object
- decouple login & score submission data parsing from controllers
- misc code clean up on login & score submission controllers
- overall code cleanup & improvements
'anticheat' does not yet perform automatic restrictions when these assertions are not met - but instead logs to my server.
the functionality is in place to perform restrictions, and will be enabled after a trial period to ensure all is well & tested.
thanks to @xxCherry & @infernalfire72 for the tips for improvements :)
> Checksum validation on score submission, login cleanup & storing of client details

- app/commands.py
It used the name column instead of safe_name, resulting in an SQL error that the safe_name column is unique.
Example: User "test 123" exists and you want to change your name to "test_123"
> Fixed check whether the user exists in changename

- app/api/init_api.py
This was an internal issue where `.host()` would only interface Starlette, creating a `Host` object which FastAPI cannot deal with.
The fix this PR provides is a subclass of FastAPI which modifies the `.openapi()` call to include the routes from the `Host` objects it contains.
> Fix OpenAPI docs not being generated

- app/api/domains/osu.py
- app/commands.py
- app/objects/player.py
Replaces the safe name creation logic with a simple function that already exists and yields the same results. Helps in case the logic has to be changed at a further point.
> Reduce code repetition on safe name creation

- app/commands.py
This is important as when you manually remove the donator privileges instead of the background task it results in the donor_end not being changed at all. If you use the givedonator command on that player again, the specified time will add up with the existing donor_end.
Example:
user1 gets donator for 10 minutes
donator privileges are removed from user1
user1 gets donator 10 minutes
Result: because the removal did not reset donor_end, the 10 minutes are added to donor_end instead of time.time()
> made rmpriv set donor_end back to 0

- app/commands.py
addpriv does not set a donator end therefore the background task will remove the donator privileges after some time anyway.
To hint users the proper way to assign donator privileges just make them unable to assign the privileges and return an error instead.
> Make users unable to assign donator privileges using !addpriv

- app/api/domains/osu.py
According to the [docs](https://osu.ppy.sh/wiki/en/Performance_points), the bonus pp formula is
```
416.6667 * (1 - 0.9994 ^ N)
```
Which does not match up here
https://github.com/osuAkatsuki/bancho.py/blob/1bc4424406bd74dbb576fc7027b4460405e19e35/app/api/domains/osu.py#L1005
Changing 0.95 to 0.9994 seems like a pointless change, but it actually has a huge affect on how bonus pp works. To achieve the maximum amount of bonus pp on bancho, you would need to set 25397 scores on ranked maps which is quite a lot. But because 0.9994 was shortened to 0.95, you would only need to set 200 scores to hit the limit.
> fix: bonus pp formula

- app/api/domains/osu.py
- app/settings.py
- migrations/base.sql
- migrations/migrations.sql
Favourite beatmaps on bancho will show in the order that you favourite them:
I'd like to do the same on bancho.py, but it isn't possible as the only two colums are `userid` and `setid`. Instead, the order is based on when the beatmap itself was inserted into the `maps` database. My only other option is to order by the beatmap's `last_update`. Adding `fav_time` allows me to sort by the time the map was favourited, and gives more flexibility for future queries. I think it would be a pretty useful addition for both me, and any other frontend/api projects.
I also added a redirect for beatmap threads. I'm aware the code will likely be [removed](https://github.com/osuAkatsuki/bancho.py/blob/592d386f70aee2c1c0833250642ea0b5ea97cd52/app/api/domains/osu.py#L1658) but I can't see a frontend making …
> Add db column to track when a user added map as a favourite; add redirect for beatmapset discussion page

- app/api/domains/cho.py
In the current state, osu! will not return anything in builds dict since server tries to get builds with stream `OsuStream.CUTTINGEDGE` for example instead of it's normal name.
> Call `.value` on release stream upon fetching build info from osu!

- app/api/domains/api.py
most places work under the assumption that pages contain 50 players on each page, which also seems more logical to me.
can be closed if too irrelevant but just something i noticed
> chore(api): change default player count on lb from 25 to 50

- app/api/domains/osu.py
After pulling the last few commits I've noticed seasonal backgrounds don't work and comes up with 
`
File "/home/sensokaku/bancho.py/app/api/domains/osu.py", line 1696, in osuSeasonal                                                                          return ORJSONResponse(app.settings.SEASONAL_BGS._items)
AttributeError: 'list' object has no attribute '_items'
`
And removing _items solved the issue.
I'm not sure if anyone else has gotten the issue (I'm also using ubuntu 22.10 LTS if that could be a factor)
> Fix broken seasonal backgrounds

- app/api/domains/osu.py
nasuya (https://nasuya.xyz/docs) is a new, efficient mirror created by me, has a cheesegull supporting api (albeit on a different URL). this pr adds support for it, as it adds some conveniences (e.g automatic direct serialization)
> feat: nasuya support

- tools/recalc.py
As of right now, if `ensure_local_osu_file` can't find a beatmap, it will fail to potentially grab it from osu! as the http client was not created.
> Create and close ClientSession when recalculating

- app/settings.py
mostly for backwards compatibility, perhaps we can change the value & eventually deprecate this support
> fix: support empty server port in config

- app/api/domains/cho.py
Pick in a mp match a std map and play it in another gamemode (catch/taiko/mania) without any problem
Pick a std map, choose another gamemode and fallback to std.
- Bug
https://user-images.githubusercontent.com/33896771/211444216-ba02ce9b-cb3b-401c-8e16-eeddb68fac2d.mp4
- With this PR
https://user-images.githubusercontent.com/33896771/211444288-9b2fc661-9126-45fb-870d-947ba0cb657b.mp4
>  Fix not being able to pick converts maps in multiplayer 

- tools/recalc.py
Previously, gamemode was not handled correctly in the pp/acc recalculation script; this addresses the issues & removes unused code.
> fix: gamemode related bugs in recalc script

- .pre-commit-config.yaml
`blacken-docs` was requesting a version of black that is out of date.
This PR fixes checks, should be merged immediately.
> fix: pre-commit conflicting deps

- app/api/v1/api.py
Fixed an issue related to `v1/get_replay` API route, which have lead to `TypeError: 'bytearray' object is not an iterator` error.
> Fix issue with v1/get_replay API route returning 0 byte files

- app/api/domains/osu.py
This change will manually strip the final space of a username to allow score submission on cases where a username ends with a space.
Resolves https://github.com/osuAkatsuki/bancho.py/issues/429
> fix: only allow one space to be stripped from score submission username

- app/commands.py
i made `!pool info` list alphabetically, then numerically
previous functionality
new functionality
i made `!pool add` list back whatever mod slot the user selected, instead of just the beatmap and pool name
previous functionality
`Peter Lambert - osu! Tutorial added to HWC22.`
new functionality
`Peter Lambert - osu! Tutorial added to HWC22 as HD1.`
please ignore the custom embeds and the "FM" entry. those are not included in this pull request.
> fix: pool information being ordered alphabetically and numerically, give full response to user on !pool add success

- app/api/v2/common/responses.py
- app/api/v2/models/__init__.py
recently, fastapi was updated to version 0.100.0, which introduced support for pydantic v2 and brought some breaking changes along with it. for bancho.py, this caused an import error immediately upon launch due to `GenericModel` being replaced by `BaseModel`. upon testing there was also a deprecation warning for the `anystr_strip_whitespace` model attribute, which has now also been renamed. :)
the offending fastapi release:
https://github.com/tiangolo/fastapi/releases/tag/0.100.0
pydantic v2 recommended adjustments:
https://github.com/pydantic/bump-pydantic#bp005-replace-genericmodel-by-basemodel
> fix: adjust for breaking changes in pydantic v2

- app/api/domains/cho.py
- app/repositories/ingame_logins.py
> refactor: ingame_logins repository

- Pipfile
- Pipfile.lock
- app/api/domains/cho.py
- app/api/domains/osu.py
- app/api/init_api.py
- app/api/v2/clans.py
- app/api/v2/common/responses.py
- app/api/v2/maps.py
- app/api/v2/players.py
- app/api/v2/scores.py
- app/commands.py
- app/repositories/ingame_logins.py
- mypy.ini
- requirements-dev.txt
> Fix mypy discovery & all type errors across source

- .github/workflows/docker-build.yaml
Added a GitHub action for building Docker images. This will output as a job artifact. Additionally, it will push to the Docker registry if the action is on `master`.
Artifacts may be used in other actions like this:
```yml
use:
runs-on: ubuntu-latest
needs: build
steps:
- name: Download artifact
uses: actions/download-artifact@v3
with:
name: docker
path: /tmp
- name: Load image
run: |
docker load --input /tmp/docker.tar
docker image ls -a     
```
#514
> feat: add docker build/push action

- .github/workflows/docker-build.yaml
secrets are not available to users without write access to the repo as they are currently configured. with this change this should not be an issue anymore as if you are pushing to master you have write access anyway. we didn't need login unless we were going to build.
> fix: workaround secrets not available

- app/repositories/players.py
This PR introduces significant change to resolve specific issue. The main change is:
- **Adding 'safe_name' Field Update**: I'm introducing an update to the `safe_name` field when updating the `name` field. This resolves the issue where the 'safe_name' field was not correctly updated when using the '!changename' command.
> fix: update safe name with name on !changename command

- app/api/domains/cho.py
- app/commands.py
- app/objects/beatmap.py
- app/objects/match.py
`Beatmap.url` returns a URL in the format `/beatmapsets/{self.set.id}/{self.id}`. However, the mode is missing here (e.g. `/beatmapsets/1/75` vs `/beatmapsets/1#osu/75`). Since we don't have an in-built way to get the string of the mode (`mode[:2]` wouldn't work since `catch` is `fruits` here), the easiest way to solve this is by simply using the `/b/{self.id}` format.
> fix: `Beatmap.url` returning an incomplete URL

- app/commands.py
When using the `!map` command to update the status of a beatmap the map is always being frozen. Currently however, the code does set frozen to true in the database, but for the local cache it only updates the status.
I noticed this when debugging #420 and this PR might offer the solution for that issue. I invalidated the cache when debugging (_cache_expired always returned true) which meant it's always being fetched from the api, which caused the status to be reverted because when checking whether it's frozen on the api check it wasn't (since it checks the cache where it was false, not the database where it's true).
> fix: ensure frozen state on database and cache are in sync on !map

- tools/generate_cf_dns_records.sh
Removed the main domain being added to the subdomains in the cloudflare DNS record generator. Importing it before this fix will cause CF to think it's a large subdomain (ex. `c.example.com.example.com`).
> fix: cloudflare dns record generator

- app/api/domains/osu.py
- app/state/__init__.py
There is an ongoing issue due to this TOCTOU bug where scores (with identical checksums) may submit more than a single time (and award duplicate pp/score/etc.) if multiple get between the start and end conditions simultaneously.
This change adds a concurrency lock around the affected area to ensure only one runs at a time.
> Per-checksum score submission locks to prevent score duplicates

- Pipfile.lock
- app/api/domains/osu.py
- app/repositories/comments.py
> refactor: comments repository

- app/api/domains/osu.py
> Remove unused handling of null beatmaps

- app/objects/player.py
This is to appease to mypy as `__eq__` technically returns `Any`. Python casts to bool anyway so this should have 0 impact other than silencing mypy.
> fix: cast `__eq__` to bool

- app/api/v1/api.py
The code enumerated through the stats dictionary of the user, but used the index in that enumeration for the mode key instead of the actual mode value, which works fine... Up until autopilot, since the 7 (rx!mania) is skipped and 8 is the proper number to use. This caused the API to give 0 rank for autopilot for any user.
> fix: Wrong index for fetching global & country rank from redis on API `/get_player_info`

- app/api/domains/cho.py
- app/objects/player.py
Adds the mods, which are already being parsed from the /np regex, to the player.last_np object.
Resolves #478
> feat: add mods to player.last_np

- .github/workflows/lint.yaml
> fix: only run the push portion of the lint action when on master

- app/commands.py
- app/repositories/map_requests.py
There are two changes introduced in this PR:
1. Group nomination requests by beatmap in the `!requests` command output. Display count of times requested, rather than individual player requests.
2. Disallow duplicate nomination requests for unique key `(map_id, player_id)`.
Sample command usage after the change:
```
22:30 cmyui: !requests
22:30 BanchoBot: The queue is clean! (0 map request(s)) | Elapsed: 870.11 μsec
22:30 *cmyui is listening to [https://osu.cmyui.xyz/beatmapsets/521936#/1820817 DJ TOTTO - Crystalia]
22:30 cmyui: !request
22:30 BanchoBot: Request submitted. | Elapsed: 22.58 msec
22:30 cmyui: !request
22:30 BanchoBot: You already have an active nomination request for that map. | Elapsed: 1.11 msec
22:30 cmyui: !requests
22:30 BanchoBot: Total requested beatmaps: 1
1x …
```
> Reduce duplication issues with map nomination requests

- app/api/domains/osu.py
- app/repositories/favourites.py
> refactor: favourites repository

- app/api/domains/osu.py
- app/objects/beatmap.py
- app/repositories/ratings.py
> refactor: ratings repository

- app/api/domains/cho.py
- app/objects/match.py
There's an ongoing issue users have reported where `host` may not correctly resolve for an active match in the `LobbyJoin` packet. Multiple server owners (@minisbett, @HorizonCode, among others) have reported this issue on numerous occasions. I've never been able to replicate this, and I've traced the code and am not sure of the root cause.
This PR will stop the bleeding and not break players who encounter the issue, as well as logging to console (& my debug server if the server owner chooses to share this data with us).
I hope to more "correctly" resolve the information once we have the information to debug the issue.
> Gracefully handle no match host on lobby join case; add debug logs

- app/commands.py
Changed the hard-coded gatari.pw download link on the !maplink command to the download link of the configured download mirror.
> Change gatari.pw to configured download endpoint

- app/api/domains/osu.py
Usually PP is always rounded, but on the `/web/osu-osz2-getscores.php` endpoint it's always just casted to an int, resulting in a different PP value than what's displayed elsewhere.
> fix: add rounding to score on getscores

- app/api/v1/api.py
- app/commands.py
- app/objects/collections.py
- app/objects/match.py
- app/repositories/tourney_pool_maps.py
- app/repositories/tourney_pools.py
- app/state/sessions.py
This PR acts to serve as an example of how to split objects/collections into repositories.
In this example, the data was simply moved out of application memory and now only exists in the SQL database. I suspect the implementation for `clans` will be very similar, as clans are made up only of persistent data (clans and clan members).
The implementation of `channels` will be somewhat similar -- because similarly there are channels and channel members, however channel members are ephemeral.
The `matches` will be a bit different - in the current bancho.py model, they're entirely ephermeral data which only exists until the server reboots. They should likely be moved to redis in the long-term, but could stay in application memory and still be encapsulated in a repository. Either would be …
> Split `MapPools` and related collections/cache into repositories

- app/api/domains/osu.py
- app/api/init_api.py
- app/bg_loops.py
- app/commands.py
- app/constants/clientflags.py
- app/constants/gamemodes.py
- app/constants/mods.py
- app/constants/privileges.py
- app/constants/regexes.py
- app/discord.py
- app/objects/achievement.py
- app/objects/channel.py
- app/objects/clan.py
- app/objects/player.py
- app/settings.py
- app/utils.py
- docker-compose.test.yml
- docker-compose.yml
- ext/Caddyfile
- ext/nginx.conf.example
- main.py
This PR removes a couple of features:
- Support for unix sockets and related checks
- Insurance that the running python version is (>=3.11)
- Support for deprecated `SERVER_ADDR` and `SERVER_PORT` config vars - now only `APP_x` variants exist
- Exception hooks to catch some cases and display them in more simple light
- Validations to INET addresses
- Debugging hooks under `_testing.runtime`
- CLI handling using argparse for `main.py` (was only used for `./main.py -V`)
All of these seem like unnecessary complexity requiring extra maintenance overhead with low value delivered.
It also migrates more direct queries to SQL to instead use `players_repo`, removes usage of `__all__` in modules, and more general cleanup.
> Remove unnecessary features to decrease maintenance/complexity overhead. + Cleanup & more repo usage.

- app/adapters/database.py
- app/api/domains/cho.py
- app/api/domains/osu.py
- app/api/v1/api.py
- app/commands.py
- app/objects/beatmap.py
- app/objects/player.py
- app/repositories/__init__.py
- app/repositories/achievements.py
- app/repositories/channels.py
- app/repositories/clans.py
- app/repositories/client_hashes.py
- app/repositories/comments.py
- app/repositories/favourites.py
- app/repositories/ingame_logins.py
- app/repositories/logs.py
- app/repositories/mail.py
- app/repositories/map_requests.py
- app/repositories/maps.py
- app/repositories/ratings.py
- app/repositories/scores.py
- app/repositories/stats.py
- app/repositories/tourney_pool_maps.py
- app/repositories/tourney_pools.py
- app/repositories/user_achievements.py
- app/repositories/users.py
- app/state/services.py
- app/usecases/user_achievements.py
- pyproject.toml
Co-authored-by: James Wilson <tsunyoku@users.noreply.github.com>
Resolves #394
> [v5.1.0] Refactor the rest of the repositories to use sqlalchemy core 1.4

- app/api/domains/cho.py
This PR fixes crashes caused by the tournament client when removing attempting to remove players who are not in the match.
Im having issue running `make lint` in my system from `setuptools` complaining and python wasn't my main language soo it would be nice to know how to run `make lint` properly
> fix: prevent crash when leaving tournament match channel

- migrations/base.sql
- migrations/migrations.sql
- pyproject.toml
> [v5.2.2] Significantly optimize performance for fetching leaderboards

- .github/workflows/docker-build.yaml
Since we have switched to poetry, we can now enable arm64 docker image builds. Some users have asked for this.
> feat: enable building arm64 docker images

- app/settings.py
Added urlib parse to redis and MySQL passwords, to ensure that passwords are URL-Safe without need to escape special characters
> Ensure that provided MySQL and Redis passwords are URL-Safe

- .github/docs/wiki/Setting-up.md
- .github/docs/wiki/locale/de-DE/Setting-up-de-DE.md
- .github/docs/wiki/locale/zh-CN/Setting-up-zh-CN.md
- Makefile
- docker-compose.test.yml
- docker-compose.yml
The use of `docker-compose` has been officially deprecated in favour of `docker compose` (part of the official Docker package). On newer distros, `docker-compose` no longer works.
> Replace use of `docker-compose` with `docker compose`.

- logging.yaml.example
> Ignore warnings from multipart.multipart logger to fix mass log spam

- app/packets.py
Change the type of the performance in functions that create the "USER_STATS" packet
N/a 
- [] I've manually tested my code
> chore: update type of pp as a result of b20250306.2

- docker-compose.test.yml
- docker-compose.yml
> fix: docker composes providing wrong env arg for mysql port

- app/api/v2/models/scores.py
Fix v2 ngeki field was lost in v2 scores models
> fix: fix v2 ngeki field in models
